version: "2"
services:
  app:
    image: busybox
    container_name: gs_app
    depends_on:
      - "nginx"

  data:
    image: busybox
    container_name: gs_data
    volumes:
      - .:/var/www

  nginx:
    image: webcodium/nginx:laravel
    container_name: gs_nginx
    volumes_from:
      - data
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_HOST: gs.local
      NGINX_HTTP_PORT: 80
      NGINX_HTTPS_PORT: 443
      NGINX_CLIENT_MAX_BODY_SIZE: 10m
      NGINX_VHOST_ROOT_DIRECTORY: /var/www/web
      FASTCGI_URL: php
    depends_on:
      - "php"

  php:
    image: php:7.2-fpm
    container_name: gs_php
    volumes_from:
      - data
    depends_on:
      - "db"
      - "redis"
    working_dir: /var/www

  db:
    image: mysql:5.7.19
    container_name: gs_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: gs
      MYSQL_PASSWORD: gs
      MYSQL_DATABASE: gs

  redis:
    image: redis:4.0.11-alpine
    container_name: gs_redis
    ports:
      - "6379:6379"
